### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by prasmaran** [OAT7963/mae_pdf_processing#5]
I am seeing below error while trying to convert the statements to CSV

1. Created a folder in Desktop with name "MAE Statements 2024" with 3 months statements downloaded into
2. Created a folder in Desktop with name "MAE Statements 2024 Excel" to get converted CSV files
3. Entered "MAE Statements Sept-Nov" without file extension
4. Chose "Maybank Debit Card"

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "MAE_PDF_File_Processor.py", line 45, in selected_processing
  File "MAE_PDF_File_Processor.py", line 545, in process_files
  File "pandas\core\generic.py", line 6643, in astype
  File "pandas\core\internals\managers.py", line 430, in astype
  File "pandas\core\internals\managers.py", line 363, in apply
  File "pandas\core\internals\blocks.py", line 758, in astype
  File "pandas\core\dtypes\astype.py", line 237, in astype_array_safe
  File "pandas\core\dtypes\astype.py", line 182, in astype_array
  File "pandas\core\dtypes\astype.py", line 133, in _astype_nansafe
ValueError: could not convert string to float: '戶號'

Should I do anything additional here? Thanks

**Comment by OAT7963** [comment]
Hi, may I know if your statement is Debit account? 

Did you download the statement directly from the website or from email? 

I just tested my latest maybank debit card statement and it is working on my end 

![image](https://github.com/user-attachments/assets/4ffa783b-28be-46ad-b15d-811b61da1146)


if you're still facing issues. Can you take a screenshot of the top section of your statement? You can cover the sensitive information. I just need to see the top section and the columns. 

for that please email to me instead of putting it here haha

ongaunter@gmail.com

**Comment by prasmaran** [comment]
Hi ~ Sure brother. Will do it soon ya. Thanks

**Comment by OAT7963** [comment]
Hi, you can try and download the program again. I've updated it.

**Comment by prasmaran** [comment]
Hi ~

My sincere apologies for not replying sooner. I got caught up with some
stuff.

Sure, I will download the patched up version and let you know ya :)

Thanks and regards,
Prasanth

**Comment by prasmaran** [comment]
Hi @OAT7963 ~

Below attached is the latest error that I receive while trying the new version

![image](https://github.com/user-attachments/assets/2942e234-2069-40e6-a297-d1f406abe290)

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "MAE_PDF_File_Processor.py", line 47, in selected_processing
  File "MAE_PDF_File_Processor.py", line 547, in process_files
  File "pandas\core\generic.py", line 6643, in astype
  File "pandas\core\internals\managers.py", line 430, in astype
  File "pandas\core\internals\managers.py", line 363, in apply
  File "pandas\core\internals\blocks.py", line 758, in astype
  File "pandas\core\dtypes\astype.py", line 237, in astype_array_safe
  File "pandas\core\dtypes\astype.py", line 182, in astype_array
  File "pandas\core\dtypes\astype.py", line 133, in _astype_nansafe
ValueError: could not convert string to float: 'ACCOUNT'

p.s **_To answer your previous question: I downloaded the statements directly from website_**

Thanks

**Comment by OAT7963** [comment]
Hi Prasanth, u got very old statement u dont mind sharing? then I can fix from there. if not quite impossible for me to troubleshoot one, because i have to guess your bank statement format from my end. 

If not its fine. Will close this issue once I get someone to share with me the same format that you have.

**Comment by prasmaran** [comment]
Hey there ~

Sure I will share one tomorrow ya. It's all in my laptop and I'm
outstation right now. Thanks for the follow up

Thanks and regards,
Prasanth

**Comment by OAT7963** [comment]
Sure, you can email to me here. You can also just share an old one, doesnt have to be a recent one. 

ongaunter@gmail.com
